export const lifepaths = [
  {
    name: "Soldier",
    skills: ["Combat Tactics", "Slug Rifle", "First Aid"],
    traitPair: ["Hardened", "Haunted"],
    prompt: "What order did you follow that still troubles your conscience?",
  },
  {
    name: "Marine",
    skills: ["Zero-G", "Energy Rifle", "Battle Dress"],
    traitPair: ["Loyal", "Reckless"],
    prompt: "Whose life did you save — and whose did you fail to?",
  },
  {
    name: "Officer",
    skills: ["Leadership", "Diplomacy", "Combat Tactics"],
    traitPair: ["Charismatic", "Burdened"],
    prompt: "What command decision defined your career?",
  },
  {
    name: "Mercenary",
    skills: ["Intimidation", "Heavy Weapons", "Streetwise"],
    traitPair: ["Ruthless", "Pragmatic"],
    prompt: "What contract did you break, and who still hunts you for it?",
  },
  {
    name: "Security Agent",
    skills: ["Recon", "Deception", "Slug Pistol"],
    traitPair: ["Watchful", "Paranoid"],
    prompt: "Who once slipped past your watch, and what was the cost?",
  },
  {
    name: "Spacer",
    skills: ["Navigation", "Zero-G", "Mechanics"],
    traitPair: ["Starwise", "Jaded"],
    prompt: "What ship felt more like home than any planet?",
  },
  {
    name: "Scout",
    skills: ["Recon", "Survival", "Navigation"],
    traitPair: ["Curious", "Lonely"],
    prompt: "What did you discover on the edge of known space?",
  },
  {
    name: "Pilot",
    skills: ["Grav Vehicle", "Zero-G", "Comms"],
    traitPair: ["Hotshot", "Steady Hand"],
    prompt: "What maneuver earned you fame — or notoriety?",
  },
  {
    name: "Explorer",
    skills: ["Zoology", "Botany", "Survival"],
    traitPair: ["Bold", "Obsessive"],
    prompt: "What strange world or creature left its mark on you?",
  },
  {
    name: "Prospector",
    skills: ["Geology", "Mechanics", "Wheeled Vehicle"],
    traitPair: ["Optimist", "Greedy"],
    prompt: "Did you strike it rich — or lose everything chasing a vein?",
  },
  {
    name: "Scholar",
    skills: ["History", "Linguistics", "Mathematics"],
    traitPair: ["Inquisitive", "Detached"],
    prompt: "What truth do you know that most refuse to believe?",
  },
  {
    name: "Physician",
    skills: ["First Aid", "Surgery", "Pharmacology"],
    traitPair: ["Compassionate", "Clinical"],
    prompt: "Whose life couldn’t you save?",
  },
  {
    name: "Scientist",
    skills: ["Physics", "Chemistry", "Computer"],
    traitPair: ["Brilliant", "Absent-Minded"],
    prompt: "What experiment changed your career forever?",
  },
  {
    name: "Xenobiologist",
    skills: ["Zoology", "Ecology", "Genetics"],
    traitPair: ["Enthralled", "Cautious"],
    prompt: "What alien lifeform still fascinates — or haunts — you?",
  },
  {
    name: "Historian",
    skills: ["History", "Sociology", "Astronomy"],
    traitPair: ["Traditionalist", "Revisionist"],
    prompt: "Which forgotten past shapes how you see the present?",
  },
  {
    name: "Diplomat",
    skills: ["Diplomacy", "Etiquette", "Empathy"],
    traitPair: ["Silver-Tongued", "Compromised"],
    prompt: "What treaty did you shape, and who did it betray?",
  },
  {
    name: "Trader",
    skills: ["Barter", "Economics", "Streetwise"],
    traitPair: ["Shrewd", "Opportunist"],
    prompt: "What deal made your fortune — or ruined you?",
  },
  {
    name: "Performer",
    skills: ["Performance", "Seduction", "Etiquette"],
    traitPair: ["Charming", "Self-Destructive"],
    prompt: "What mask do you wear in public that hides your truth?",
  },
  {
    name: "Priest",
    skills: ["Empathy", "Willpower", "Sociology"],
    traitPair: ["Devout", "Doubtful"],
    prompt: "Who placed their faith in you — and did you uphold it?",
  },
  {
    name: "Politician",
    skills: ["Leadership", "Diplomacy", "Deception"],
    traitPair: ["Ambitious", "Jaded"],
    prompt: "What promise did you make that you never kept?",
  },
  {
    name: "Criminal",
    skills: ["Streetwise", "Deception", "Slug Pistol"],
    traitPair: ["Connected", "Wanted"],
    prompt: "What job went wrong and who did it hurt?",
  },
  {
    name: "Smuggler",
    skills: ["Navigation", "Recon", "Barter"],
    traitPair: ["Bold", "Two-Faced"],
    prompt: "What was your most dangerous cargo?",
  },
  {
    name: "Hacker",
    skills: ["Computer", "Electronics", "Deception"],
    traitPair: ["Elusive", "Obsessed"],
    prompt: "Whose secrets are you still keeping?",
  },
  {
    name: "Drifter",
    skills: ["Survival", "Athletics", "Streetwise"],
    traitPair: ["Lucky", "Desperate"],
    prompt: "What’s the closest you came to dying in the void/wilderness?",
  },
  {
    name: "Rebel",
    skills: ["Intimidation", "Leadership", "Demolitions"],
    traitPair: ["Zealous", "Burned Out"],
    prompt: "What cause did you fight for — and was it worth it?",
  },
]